language: r
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" _R_CHECK_TESTS_NLINES_=0

jobs:
  include:
    - r: oldrel
    - r: release
      before_install:
        - "curl -L https://xran.yihui.org/.gitconfig -o ~/.gitconfig"
      after_success:
        - "(curl -L https://xran.yihui.org/r-xran | bash)"
    - r: devel
